apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: sitecontagemk8s0 
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: sitecontagemk8s0 
    spec:
      containers:
        - name: sitecontagemk8s0 
          image: groffeazuredevops.azurecr.io/sitecontagemk8s0
          ports:
          - containerPort: 80
          env:
            - name: MensagemVariavel
              value: Utilizando o Azure Kubernetes Service (AKS) durante o Treinamento do Azure na Prática
